ccslol/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('', include('page_home.urls')),
    path('about/', include('page_about.urls')),
    path('blog/', include('page_blog.urls')),
    path('playoffs/', include('page_playoffs.urls')),
    path('schedule/', include('page_schedule.urls')),
    path('standings/', include('page_standings.urls')),
    path('twitch/', include('page_twitch.urls')),
    # Non user-facing
    path('api/', include('backend_api.urls')),
    path('admin/', admin.site.urls),
    path('staff/', include('auth_staff.urls')),
    # Timezone detection (django-tz-detect)
    re_path(r'^tz_detect/', include('tz_detect.urls'))
]

page_news/urls.py
from django.urls import path

from . import views

app_name = 'page_news'
urlpatterns = [
    path('', views.root, name='root'),
    path('write', views.write, name='write'),
]

page_news/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, reverse

# Create your views here.

def root(request):
    return render(request, 'page_news_html/main.html')


def write(request):
    if request.user.is_authenticated:
        return render(request, 'page_news_html/write.html')
    messages.add_message(request, messages.WARNING, 'You must be signed in to do that!')
    return redirect(reverse("page_home:root"))

page_news/templates/page_news_html/main.html
{% extends "page_base.html" %}
{% load static %}


{% block fonts %}
{{ block.super }}
{% endblock %}


{% block style %}
{{ block.super }}
<link type="text/css" rel="stylesheet" href="{% static 'styles/parallax.css' %}">
{% endblock %}


{% block script %}
{{ block.super }}
{% endblock %}


{% block title %}
{{ block.super }}
{% endblock %}


{% block nav-news %}
<span class="nav-link">Articles</span>
{% endblock %}


{% block header %}
{{ block.super }}
{% endblock %}


{% block content %}
<div id="news_parallax" class="parallax-window parallax-spacer" data-speed="0.3" data-parallax="scroll" data-image-src="{% static 'assets/about_bg.jpg' %}"></div>

<div class="col-xl-7 col-lg-8 col-md-9 col-11 mx-auto px-md-4 pt-4">
    <p> hello body </p>
    <p> hello body </p>
    <p> hello body </p>
    <p> hello body </p>
    <p> hello body </p>
    <p> hello body </p>
    <p> hello body </p>
    <p> hello body </p>
    <p> hello body </p>
    <p> hello body </p>
    <p> hello body </p>
    <p> hello body </p>
    <p> hello body </p>
    <p> hello body </p>
    <p> hello body </p>
    <p> hello body </p>
    <p> hello body </p>
</div>

{% endblock %}


{% block footer %}
{{ block.super }}
{% endblock %}


{% block bottom_script %}
{% endblock %}

page_news/templates/page_news_html/write.html
{% extends "page_base.html" %}
{% load static %}


{% block fonts %}
{{ block.super }}
{% endblock %}


{% block style %}
{{ block.super }}
<link type="text/css" rel="stylesheet" href="{% static 'styles/parallax.css' %}">
{% endblock %}


{% block script %}
{{ block.super }}
{% endblock %}


{% block title %}
{{ block.super }}
{% endblock %}


{% block nav-news %}
<span class="nav-link">Articles</span>
{% endblock %}


{% block header %}
{{ block.super }}
{% endblock %}


{% block content %}
<div id="news_parallax" class="parallax-window parallax-spacer" data-speed="0.3" data-parallax="scroll" data-image-src="{% static 'assets/about_bg.jpg' %}"></div>

<div class="col-xl-7 col-lg-8 col-md-9 col-11 mx-sm-auto px-md-4 pt-4">
    <form id="article-form" class="needs-validation" action="" enctype="multipart/form-data" novalidate>
        {% csrf_token %}

        <div class="form-group">
            <label for="article-title">Article Title</label>
            <input name="article_title" id="article-title" type="text" class="form-control" placeholder="Write your title here..." maxlength="256" required>
            <div id="article-title-error" class="invalid-feedback">
                Must enter a title.
            </div>
        </div>

        <br>

        <div class="form-group">
            <label for="article-content">Article Content</label>
            <textarea name="article_content" id="article-content" class="form-control" placeholder="Write your article here..." required> </textarea>
            <div id="article-content-error" class="invalid-feedback">
                Must enter content for the article.
            </div>
        </div>

        <br>

        <button name='submit' type='submit' class="btn btn-primary">Submit</button>
    </form>
</div>

{% endblock %}


{% block footer %}
{{ block.super }}
{% endblock %}


{% block bottom_script %}
<script src="{% static 'scripts/tinymce/tinymce.min.js' %}"></script>
<script>
    tinymce.init({
        selector: '#article-content',  // change this value according to your HTML
        height: 400,
        plugins: [
            'advlist autolink lists link image charmap print preview anchor',
            'searchreplace visualblocks code fullscreen codesample',
            'insertdatetime media table paste imagetools wordcount'
        ],
        toolbar: 'undo redo | styleselect | fontselect fontsizeselect bold italic | forecolor | alignleft aligncenter alignright alignjustify | link image | bullist numlist outdent indent | codesample',
    });

    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function () {
        'use strict';

        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.querySelectorAll('.needs-validation');

        // Loop over them and prevent submission
        Array.prototype.slice.call(forms).forEach(function (form) {
            form.addEventListener('submit', function (event) {
                if (!form.checkValidity()) {
                    event.preventDefault();
                    event.stopPropagation();
                }

                form.classList.add('was-validated');
            }, false);
        });
    })();

    $("#article-form").submit(function (event) {
        // Do not actually "submit" the form.
        event.preventDefault();

        // Stop the submission if the form is incomplete
        if ($(this)[0].checkValidity() === false) {return;}

        var form_values = $(this).serializeArray();
        $.ajax({
            url: "{% url 'api_database:news_post' %}",
            type: 'post',
            data: form_values,
            dataType: 'json',
            success: function (response) {
                window.location.replace("{% url 'page_news:root' %}");
            },
            error: function (response) {
                alert("Something went wrong.");
            }
        });
    });
</script>
{% endblock %}