backend_api/urls.py
from django.urls import path

from . import views

app_name = 'backend_api'
urlpatterns = [
    path('blog/post', views.blog_post, name='blog_post'),
    path('blog/edit', views.blog_edit, name='blog_edit'),
]

ccslol/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('', include('page_home.urls')),
    path('about/', include('page_about.urls')),
    path('blog/', include('page_blog.urls')),
    path('playoffs/', include('page_playoffs.urls')),
    path('schedule/', include('page_schedule.urls')),
    path('standings/', include('page_standings.urls')),
    path('twitch/', include('page_twitch.urls')),
    # Non user-facing
    path('api/', include('backend_api.urls')),
    path('admin/', admin.site.urls),
    path('staff/', include('auth_staff.urls')),
    # Timezone detection (django-tz-detect)
    re_path(r'^tz_detect/', include('tz_detect.urls'))
]

page_blog/urls.py
from django.urls import path

from . import views

app_name = 'page_blog'
urlpatterns = [
    path('', views.root, name='root'),
    path('write', views.write_article, name='write_article'),
    path('edit/<int:article_id>', views.edit_article, name='edit_article'),
    path('article/<int:article_id>', views.view_article, name='view_article'),
]

page_blog/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, reverse
from django.utils import timezone

from backend_database.models import Article

# Create your views here.

def root(request):
    try:
        count = int(request.GET.get('page', '1'))
    except:
        count = 1
    if count < 1:
        count = 1

    per_page = 10
    page_count = (Article.objects.count() // per_page) + 1
    page_range = range(1, page_count + 1)

    if count not in page_range:
        return redirect('{}?page=1'.format(reverse("page_blog:root")))

    articles = Article.objects.order_by("-date_posted")[per_page * (count - 1):per_page * count]

    context = {
        "articles": articles,
        "page_range": page_range,
        "page_current": count,
        "page_max": (Article.objects.count() // per_page) + 1,
    }

    return render(request, 'page_blog_html/main.html', context)


def write_article(request):
    if request.user.is_authenticated:
        return render(request, 'page_blog_html/write.html')
    else:
        messages.add_message(request, messages.WARNING, 'You must be signed in to do that!')
    return redirect(reverse("page_blog:root"))


def edit_article(request, article_id):
    if request.user.is_authenticated:
        article_query = Article.objects.filter(id=article_id)

        if article_query.exists():
            context = {
                "article": article_query[0]
            }

            return render(request, 'page_blog_html/edit.html', context)
    else:
        messages.add_message(request, messages.WARNING, 'You must be signed in to do that!')

    return redirect(reverse("page_blog:root"))


def view_article(request, article_id):
    article_query = Article.objects.filter(id=article_id)
    
    if article_query.exists():
        context = {
            "article": article_query[0]
        }
        
        return render(request, 'page_blog_html/article.html', context)
    
    return redirect(reverse("page_blog:root"))


# Timezones
import pytz

def convert_to_localtime(utctime):
    utc = utctime.replace(tzinfo=pytz.UTC)
    return utc.astimezone(timezone.get_current_timezone())

page_blog/templates/page_blog_html/article.html
{% extends "page_blog_html/article_template.html" %}
{% load static %}


{% block fonts %}
{{ block.super }}
<link href="https://fonts.googleapis.com/css2?family=Kaisei+HarunoUmi:wght@500&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Raleway&display=swap" rel="stylesheet">
{% endblock %}


{% block style %}
{{ block.super }}
<link type="text/css" rel="stylesheet" href="{% static 'styles/page_blog_article.css' %}">
{% endblock %}


{% block article %}
<a href="{% url 'page_blog:root' %}">&laquo; Back</a>
<h2 class="article-title">
    {{ article.title }}
</h2>
<p class="article-post-details">
    Posted by {{ article.author }} | {{ article.date_posted|date:"F j, o, g:i A" }}
    {% if article.date_posted != article.last_edited %}
    <br>
    <span style="font-size:12px">
        Last edited by {{ article.last_edited_by }} | {{ article.last_edited|date:"F j, o, g:i A" }}
    </span>
    {% endif %}
    <br>
    {% if user.is_authenticated %}
    <a href="{% url 'page_blog:edit_article' article_id=article.id %}" role="button">Edit</a>
    {% endif %}
</p>
<div class="article-content">
    {{ article.content|safe }}
</div>
{% endblock %}

page_blog/templates/page_blog_html/article_template.html
{% extends "page_base.html" %}
{% load static %}


{% block fonts %}
{{ block.super }}
{% endblock %}


{% block style %}
{{ block.super }}
<link type="text/css" rel="stylesheet" href="{% static 'styles/parallax.css' %}">
{% endblock %}


{% block script %}
{{ block.super }}
{% endblock %}


{% block title %}
{{ block.super }}
{% endblock %}


{% block nav-blog %}
active
{% endblock %}


{% block header %}
<div id="blog_parallax" class="parallax-window parallax-spacer" data-speed="0.3" data-parallax="scroll" data-image-src="{% static 'assets/about_bg.jpg' %}"></div>
{% endblock %}


{% block content %}
<div class="col-xl-7 col-lg-8 col-md-9 col-11 mx-auto px-md-4 pt-4">
    {% block article %}
    {% endblock %}
</div>
{% endblock %}


{% block footer %}
{{ block.super }}
{% endblock %}


{% block bottom_script %}
{% endblock %}

page_blog/templates/page_blog_html/edit.html
{% extends "page_base.html" %}
{% load static %}


{% block fonts %}
{{ block.super }}
{% endblock %}


{% block style %}
{{ block.super }}
<link type="text/css" rel="stylesheet" href="{% static 'styles/parallax.css' %}">
{% endblock %}


{% block script %}
{{ block.super }}
{% endblock %}


{% block title %}
{{ block.super }}
{% endblock %}


{% block nav-blog %}
active
{% endblock %}


{% block header %}
<div id="blog_parallax" class="parallax-window parallax-spacer" data-speed="0.3" data-parallax="scroll" data-image-src="{% static 'assets/about_bg.jpg' %}"></div>
{% endblock %}


{% block content %}
<div class="col-xl-7 col-lg-8 col-md-9 col-11 mx-sm-auto px-md-4 pt-4">
    <form id="article-form" class="needs-validation" action="" enctype="multipart/form-data" novalidate>
        {% csrf_token %}

        <div class="form-group">
            <label for="article-title">Article Title</label>
            <input name="article_title" id="article-title" type="text" class="form-control" value="{{ article.title }}" placeholder="Write your title here..." maxlength="256" required>
            <div id="article-title-error" class="invalid-feedback">
                Must enter a title.
            </div>
        </div>

        <br>

        <div class="form-group">
            <label for="article-content">Article Content</label>
            <textarea name="article_content" id="article-content" class="form-control" placeholder="Write your article here..." required>
                {{ article.content|safe }}
            </textarea>
            <div id="article-content-error" class="invalid-feedback">
                Must enter content for the article.
            </div>
        </div>

        <br>

        <input name="article_id" id="article-id" type="hidden" value="{{ article.id }}">
        <button name='submit' type='submit' class="btn btn-primary">Submit</button>
    </form>
</div>

{% endblock %}


{% block footer %}
{{ block.super }}
{% endblock %}


{% block bottom_script %}
<script src="{% static 'scripts/tinymce/tinymce.min.js' %}"></script>
<script>
    tinymce.init({
        selector: '#article-content',  // change this value according to your HTML
        height: 400,
        plugins: [
            'advlist autolink lists link image charmap print preview anchor',
            'searchreplace visualblocks code fullscreen codesample',
            'insertdatetime media table paste imagetools wordcount'
        ],
        toolbar: 'undo redo | styleselect | fontselect fontsizeselect bold italic | forecolor | alignleft aligncenter alignright alignjustify | link image | bullist numlist outdent indent | codesample',
        setup: function (editor) {
            editor.on('change', function (e) {
                editor.save();
            });
        }
    });

    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function () {
        'use strict';

        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.querySelectorAll('.needs-validation');

        // Loop over them and prevent submission
        Array.prototype.slice.call(forms).forEach(function (form) {
            form.addEventListener('submit', function (event) {
                if (!form.checkValidity()) {
                    event.preventDefault();
                    event.stopPropagation();
                }

                form.classList.add('was-validated');
            }, false);
        });
    })();

    $("#article-form").submit(function (event) {
        // Do not actually "submit" the form.
        event.preventDefault();

        // Stop the submission if the form is incomplete
        if ($(this)[0].checkValidity() === false) {return;}

        var form_values = $(this).serializeArray();
        $.ajax({
            url: "{% url 'backend_api:blog_edit' %}",
            type: 'post',
            data: form_values,
            dataType: 'json',
            success: function (response) {
                window.location.replace("{% url 'page_blog:view_article' article_id=article.id %}");
            },
            error: function (response) {
                alert("Something went wrong.");
            }
        });
    });
</script>
{% endblock %}

page_blog/templates/page_blog_html/main.html
{% extends "page_base.html" %}
{% load static %}


{% block fonts %}
{{ block.super }}
{% endblock %}


{% block style %}
{{ block.super }}
<link type="text/css" rel="stylesheet" href="{% static 'styles/parallax.css' %}">
<link type="text/css" rel="stylesheet" href="{% static 'styles/page_blog.css' %}">
{% endblock %}


{% block script %}
{{ block.super }}
{% endblock %}


{% block title %}
{{ block.super }}
{% endblock %}


{% block nav-blog %}
active
{% endblock %}


{% block header %}
<div id="blog_parallax" class="parallax-window parallax-spacer" data-speed="0.3" data-parallax="scroll" data-image-src="{% static 'assets/about_bg.jpg' %}"></div>
{% endblock %}


{% block content %}
<div class="col-xl-7 col-lg-8 col-md-9 col-11 mx-auto px-md-4 pt-4">
    {% if user.is_authenticated %}
    <a class="btn btn-outline-primary" href="{% url 'page_blog:write_article' %}" role="button">Write a new article</a>
    {% endif %}

    <div id="article-list">
        {% if articles %}
            {% for article in articles %}
            <div class="article-post">
                <h5 class="article-title">
                    <a href="{% url 'page_blog:view_article' article_id=article.id %}">{{ article.title }}</a>
                </h5>
                <p class="article-post-details">
                    {{ article.date_posted|date:"F j, o, g:i A" }} | {{ article.author }}
                </p>
            </div>
            {% if not forloop.last %}
            <hr>
            {% endif %}
            {% endfor %}
        {% else %}
        <h4>No articles have been written yet!</h4>
        {% endif %}
        
    </div>
    <nav>
        <ul class="pagination">
            <li class="page-item
                       {% if page_current <= 1 %}
                       disabled
                       {% endif %}
                       ">
                <a class="page-link" href="{% url 'page_blog:root' %}?page={{ page_current|add:"-1" }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% for i in page_range %}
            <li class="page-item 
                       {% if i == page_current %}
                       active
                       {% endif %}
                       ">
                <a class="page-link" href="{% url 'page_blog:root' %}?page={{ i }}">
                    {{ i }}
                </a>
            </li>
            {% endfor %}
            <li class="page-item
                       {% if page_current >= page_max %}
                       disabled
                       {% endif %}
                       ">
                <a class="page-link" href="{% url 'page_blog:root' %}?page={{ page_current|add:"1" }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
      </nav>
</div>

{% endblock %}


{% block footer %}
{{ block.super }}
{% endblock %}


{% block bottom_script %}
{% endblock %}

page_blog/templates/page_blog_html/write.html
{% extends "page_base.html" %}
{% load static %}


{% block fonts %}
{{ block.super }}
{% endblock %}


{% block style %}
{{ block.super }}
<link type="text/css" rel="stylesheet" href="{% static 'styles/parallax.css' %}">
{% endblock %}


{% block script %}
{{ block.super }}
{% endblock %}


{% block title %}
{{ block.super }}
{% endblock %}


{% block nav-blog %}
active
{% endblock %}


{% block header %}
<div id="blog_parallax" class="parallax-window parallax-spacer" data-speed="0.3" data-parallax="scroll" data-image-src="{% static 'assets/about_bg.jpg' %}"></div>
{% endblock %}


{% block content %}
<div class="col-xl-7 col-lg-8 col-md-9 col-11 mx-sm-auto px-md-4 pt-4">
    <form id="article-form" class="needs-validation" action="" enctype="multipart/form-data" novalidate>
        {% csrf_token %}

        <div class="form-group">
            <label for="article-title">Article Title</label>
            <input name="article_title" id="article-title" type="text" class="form-control" placeholder="Write your title here..." maxlength="256" required>
            <div id="article-title-error" class="invalid-feedback">
                Must enter a title.
            </div>
        </div>

        <br>

        <div class="form-group">
            <label for="article-content">Article Content</label>
            <textarea name="article_content" id="article-content" class="form-control" placeholder="Write your article here..." required></textarea>
            <div id="article-content-error" class="invalid-feedback">
                Must enter content for the article.
            </div>
        </div>

        <br>

        <button name='submit' type='submit' class="btn btn-primary">Submit</button>
    </form>
</div>

{% endblock %}


{% block footer %}
{{ block.super }}
{% endblock %}


{% block bottom_script %}
<script src="{% static 'scripts/tinymce/tinymce.min.js' %}"></script>
<script>
    tinymce.init({
        selector: '#article-content',  // change this value according to your HTML
        height: 400,
        plugins: [
            'advlist autolink lists link image charmap print preview anchor',
            'searchreplace visualblocks code fullscreen codesample',
            'insertdatetime media table paste imagetools wordcount'
        ],
        toolbar: 'undo redo | styleselect | fontselect fontsizeselect bold italic | forecolor | alignleft aligncenter alignright alignjustify | link image | bullist numlist outdent indent | codesample',
        setup: function (editor) {
            editor.on('change', function (e) {
                editor.save();
            });
        }
    });

    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function () {
        'use strict';

        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.querySelectorAll('.needs-validation');

        // Loop over them and prevent submission
        Array.prototype.slice.call(forms).forEach(function (form) {
            form.addEventListener('submit', function (event) {
                if (!form.checkValidity()) {
                    event.preventDefault();
                    event.stopPropagation();
                }

                form.classList.add('was-validated');
            }, false);
        });
    })();

    $("#article-form").submit(function (event) {
        // Do not actually "submit" the form.
        event.preventDefault();

        // Stop the submission if the form is incomplete
        if ($(this)[0].checkValidity() === false) {return;}

        var form_values = $(this).serializeArray();
        $.ajax({
            url: "{% url 'backend_api:blog_post' %}",
            type: 'post',
            data: form_values,
            dataType: 'json',
            success: function (response) {
                window.location.replace("{% url 'page_blog:root' %}");
            },
            error: function (response) {
                alert("Something went wrong.");
            }
        });
    });
</script>
{% endblock %}